### ISSUE TITLE
Segfaults when compiled against python 3.11

### ISSUE THREAD

**Issue by wom-bat** [grisha/mod_python#124]
`Thread 5 "apache2" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fb5e37fe6c0 (LWP 10393)]
__new_sem_post (sem=0x21) at ./nptl/sem_post.c:35
35      ./nptl/sem_post.c: No such file or directory.
`
I see this backtrace:
`__new_sem_post (sem=0x21) at ./nptl/sem_post.c:35
35      ./nptl/sem_post.c: No such file or directory.
(gdb) bt
#0  __new_sem_post (sem=0x21) at ./nptl/sem_post.c:35
#1  0x00007fb5eb1c23e9 in PyThread_release_lock ()
   from target:/lib/x86_64-linux-gnu/libpython3.11.so.1.0
#2  0x00007fb5eb29b9a0 in ?? ()
   from target:/lib/x86_64-linux-gnu/libpython3.11.so.1.0
#3  0x00007fb5eb7441aa in ?? ()
   from target:/usr/lib/apache2/modules/mod_python.so
#4  0x00005611d926dbf0 in ap_run_handler ()
#5  0x00005611d926e1d6 in ap_invoke_handler ()
#6  0x00005611d9286747 in ap_process_async_request ()
#7  0x00005611d9282af3 in ?? ()
#8  0x00005611d92778a0 in ap_run_process_connection ()
#9  0x00007fb5eb7c6a06 in ?? ()
   from target:/usr/lib/apache2/modules/mod_mpm_event.so
#10 0x00007fb5eb7c745a in ?? ()
   from target:/usr/lib/apache2/modules/mod_mpm_event.so
#11 0x00007fb5ec06dfd4 in start_thread (arg=<optimized out>)
    at ./nptl/pthread_create.c:442
#12 0x00007fb5ec0ee5bc in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
`

**Comment by grisha** [comment]
Is this the latest master? 'cause I think we fixed something looking very similar in #100
