### ISSUE TITLE
Python3: SyntaxError occured in psp.py

### ISSUE THREAD

**Issue by thinkAmi** [grisha/mod_python#61]
SyntaxError occured using Python3:

import `psp.py` file.

```python
# test_psp.py
from psp import PSP

pass
```

run.

```
$ python --version
Python 3.6.1

$ pwd
/path/to/lib/python

$ python mod_python/test_psp.py 
Traceback (most recent call last):
  File "mod_python/test_psp.py", line 1, in <module>
    from psp import PSP
  File "/path/to/lib/python/mod_python/psp.py", line 280
    raise et, ev, etb
            ^
SyntaxError: invalid syntax
```

**Comment by thinkAmi** [comment]
fixed PR #62
