### ISSUE TITLE
Unable to accept GET requests

### ISSUE THREAD

**Issue by andocromn** [grisha/mod_python#78]
I am trying to accept GET requests, I am following the form.py example from the tutorial.  I am getting the following error

Mod_python error: "PythonHandler mod_python.publisher"

Traceback (most recent call last):

File "/usr/local/lib/python3.5/dist-packages/mod_python/apache.py", line 398, in HandlerDispatch
result = obj(req)

File "/usr/local/lib/python3.5/dist-packages/mod_python/publisher.py", line 222, in handler
published = publish_object(req, object)

File "/usr/local/lib/python3.5/dist-packages/mod_python/publisher.py", line 445, in publish_object
req.form = util.FieldStorage(req, keep_blank_values=1)

File "/usr/local/lib/python3.5/dist-packages/mod_python/util.py", line 250, in init
self.add_field(pair[0], pair[1])

File "/usr/local/lib/python3.5/dist-packages/mod_python/util.py", line 398, in add_field
item = StringField(value)

File "/usr/local/lib/python3.5/dist-packages/mod_python/util.py", line 159, in new
return bytes.new(self, value)

TypeError: string argument without an encoding

**Comment by andocromn** [comment]
made some changes, now getting a pretty clear error

Mod_python error: "PythonHandler mod_python.publisher"

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/mod_python/apache.py", line 398, in HandlerDispatch
    result = obj(req)

  File "/usr/local/lib/python3.5/dist-packages/mod_python/publisher.py", line 222, in handler
    published = publish_object(req, object)

  File "/usr/local/lib/python3.5/dist-packages/mod_python/publisher.py", line 445, in publish_object
    req.form = util.FieldStorage(req, keep_blank_values=1)

  File "/usr/local/lib/python3.5/dist-packages/mod_python/util.py", line 250, in __init__
    self.add_field(pair[0], pair[1])

  File "/usr/local/lib/python3.5/dist-packages/mod_python/util.py", line 398, in add_field
    item = StringField(value)

  File "/usr/local/lib/python3.5/dist-packages/mod_python/util.py", line 159, in __new__
    return bytes.__new__(self, value)

TypeError: string argument without an encoding
